# Generated by Django 5.2.1 on 2025-06-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pago',
            name='pasarela',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='unidadMedida',
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.carrito')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.producto')),
                ('unidadMedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.unidadmedida')),
            ],
            options={
                'unique_together': {('carrito', 'producto', 'unidadMedida')},
            },
        ),
    ]
