# Generated by Django 5.2.1 on 2025-07-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_producto',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_productos/'),
        ),
    ]
