# Generated by Django 5.2.1 on 2025-06-16 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='id_jugador',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_almacen',
            new_name='almacen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_promocion',
            new_name='promocion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_proveedor',
            new_name='proveedor',
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('stock_actual', models.IntegerField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUDH.producto')),
            ],
        ),
    ]
