# Generated by Django 5.2.1 on 2025-06-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0002_rename_id_jugador_jugador_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='almacen',
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='producto',
            name='almacen',
            field=models.ManyToManyField(through='WebUDH.Kardex', to='WebUDH.almacen'),
        ),
    ]
