# Generated by Django 5.2.1 on 2025-07-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0002_carrito_producto_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito_producto',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
