# Generated by Django 5.2.1 on 2025-06-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0002_alter_pedido_unique_together_remove_pago_pasarela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('hincha', 'Hincha')], default='hincha', max_length=20),
        ),
    ]
