# Generated by Django 5.2.1 on 2025-07-13 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0003_remove_carrito_producto_imagen_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebUDH.carrito'),
        ),
    ]
