# Generated by Django 5.2.1 on 2025-06-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0003_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_jugadores/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('hincha', 'Hincha')], default='hincha', max_length=30),
        ),
    ]
