# Generated by Django 5.2.1 on 2025-07-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0004_alter_producto_almacen_alter_producto_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='historias/'),
        ),
    ]
