# Generated by Django 5.2.1 on 2025-07-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0004_pedido_carrito'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together=set(),
        ),
    ]
