# Generated by Django 5.2.1 on 2025-06-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0004_jugador_imagen_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='altura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nacionalidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='peso',
            field=models.FloatField(),
        ),
    ]
