# Generated by Django 5.2.1 on 2025-07-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0004_alter_producto_almacen_alter_producto_usuario_and_more'),
        ('WebUDH', '0005_alter_jugador_altura_alter_jugador_id_and_more'),
    ]

    operations = [
    ]
