# Generated by Django 5.2.1 on 2025-07-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0005_historia_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='titulo',
            new_name='nombreHistoria',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
