# Generated by Django 5.2.1 on 2025-07-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0006_merge_20250703_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebUDH.administrador'),
        ),
    ]
