# Generated by Django 5.2.1 on 2025-07-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebUDH', '0007_alter_partido_administrador'),
        ('WebUDH', '0007_rename_imagen_url_post_historia_imagen_and_more'),
    ]

    operations = [
    ]
